[package]
name = "sovr-media"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lib]
name = "sovr_media"
path = "src/lib.rs"
