[package]
name = "sovr-graph"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
once_cell = "1"
parking_lot = "0.12"

[features]
default = ["std"]
std = []

[lib]
name = "sovr_graph"
path = "src/lib.rs"
