[package]
name = "sovr-moderation"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"

[dependencies]
once_cell = "1"
parking_lot = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lib]
name = "sovr_moderation"
path = "src/lib.rs"
