name: sovr_desktop
version: 0.1.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
