name: checksums
on:
  workflow_run:
    workflows: ["release"]
    types: [completed]
jobs:
  sign:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Download release assets
        uses: robinraju/release-downloader@v1.11
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.event.workflow_run.head_branch }}
          extract: false
      - name: Generate SHA256SUMS
        run: |
          shasum -a 256 * > SHA256SUMS
      - name: Sign with minisign
        run: |
          echo "${MINISIGN_KEY}" > key.sec
          minisign -S -s key.sec -m SHA256SUMS
        env:
          MINISIGN_KEY: ${{ secrets.MINISIGN_PRIVATE }}
      - name: Upload checksums to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            SHA256SUMS
            SHA256SUMS.minisig
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
